name: backend

on:
  push:
    branches: ["main"]

jobs:
  deploy_team:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        env: [15mintableback-sjw, cicd-backend-hjhong, 15mintable-back-chan]

    environment: ${{ matrix.env }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: install JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
            
      - name: create_properties_and_buils_push
        shell: bash
        run: |
          set -euo pipefail

          echo "${{ secrets.APPLICATION_PROPERTIES }}" | base64 --decode > ./src/main/resources/application.properties
          chmod +x ./mvnw

          ./mvnw clean package -DskipTests

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            sudo docker compose -f backend-compose.yml pull
            sudo docker compose -f backend-compose.yml down
            sudo docker compose -f backend-compose.yml up -d


  
